### PR TITLE
add cluster status view

### PR DESCRIPTION
**Pull request by buaazp**
Add a `/cluster` view as default view. Old `home` move to `/node`.
Looks like below:
memcached-ui

### CODE REVIEW

**Comment by kitelife** [comment]
great! It may be better to add some actions, such as: set, delete, in cluster view.

**Comment by buaazp** [comment]
Click the `panel-heading` of one node will enter the `node` view. I think node actions should in `node` view~

**Comment by kitelife** [comment]
In some case, we may need to do some action on all mc instances.

**Comment by buaazp** [comment]
That is indeed a special case, and dangerous.
Maybe I will implement this feature in the future~

**Comment by kitelife** [comment]
Yes, it is dangerous. Thanks.

😄  Our cluster in production env has only 3 instances.

**Comment by kitelife** [comment]
@buaazp Your blog is great, I has read some posts last year.

**Comment by buaazp** [comment]
😂 Long time no posts in the blog. Work in the company is endless...

**Comment by kitelife** [comment]
😆

**Pull request merged**
